### ISSUE TITLE
Get layout back to normal

### ISSUE THREAD

**Issue by Dustin-Mikusko** [adamsjr8576/Refactor-Tractor#1]
It looks like the tiles were spread throughout the page, rather than all lined up all to the left. We should get that layout back to a normal layout. Then from there we can divide and conquer on getting the scalability working for various screen sizes.

**Comment by adamsjr8576** [comment]
It looks like they have a div with a class of grid that contains all of the cards - we could use grid-template on that class and then assign the areas to the specific cards.
