### ISSUE TITLE
grid styling via js package - packery

### ISSUE THREAD

**Issue by adamsjr8576** [adamsjr8576/Refactor-Tractor#18]
used to import masonry layout that will format the grid and we need to reimplement it.

**Comment by Dustin-Mikusko** [comment]
@Jessmaxim303 if you are ok with getting started on this, that will give us a nice jump into the weekend

**Comment by Jessmaxim303** [comment]
@adamsjr8576 @Dustin-Mikusko - Thanks for sending me over the great documentations on this. Let me look over it and hopefully get that working again this afternoon. I'll contact you if I have any questions.

**Comment by adamsjr8576** [comment]
https://packery.metafizzy.co/layout.html: The things that I saw, which looks like it using this package are, on line 148 of index.html and line 69 of script.js code that is commented out - also their sections (cards) all have a class of "grid-item" which looks like is referencing Packery, as well as a class on the parent-div ".grid".
